# Generated by Django 2.2.5 on 2022-01-13 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30, unique=True)),
                ('offer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=40, unique=True)),
                ('price', models.FloatField()),
                ('finalprice', models.FloatField(default=0)),
                ('img1', models.ImageField(blank=True, upload_to='productimage')),
                ('img2', models.ImageField(blank=True, upload_to='productimage')),
                ('img3', models.ImageField(blank=True, upload_to='productimage')),
                ('desc', models.TextField(max_length=100)),
                ('offer', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.Category')),
            ],
        ),
    ]
