# Generated by Django 2.2.5 on 2022-01-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_auto_20220120_1835'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('sub_tot', models.FloatField()),
                ('count', models.IntegerField(default=0)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Userprofile')),
            ],
        ),
    ]
