# Generated by Django 2.2.5 on 2022-01-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
