# Generated by Django 2.2.5 on 2022-01-22 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_auto_20220120_1835'),
        ('landing', '0005_useraddr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub_tot', models.FloatField()),
                ('qty', models.IntegerField()),
                ('addr', models.TextField(max_length=800)),
                ('pay', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Userprofile')),
            ],
        ),
    ]
