# Generated by Django 2.2.5 on 2022-01-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
