# Generated by Django 2.2.5 on 2022-01-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_remove_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
