# Generated by Django 2.2.5 on 2022-02-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_coupon'),
        ('landing', '0009_auto_20220125_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Coupon'),
        ),
    ]
