# Generated by Django 2.2.5 on 2022-02-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Userprofile'),
        ),
    ]
