# Generated by Django 2.2.5 on 2022-02-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20220209_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
